### ISSUE TITLE
no buttons are displayed 

### ISSUE THREAD

**Issue by kerolloz** [jgoday/vscode-exercism-extension#2]
https://github.com/jgoday/vscode-exercism-extension/blob/0b6f4e89249317c7f67bf9d520faedda81814e1c/package.json#L31-L34
Hey @jgoday, :smiley: 
I updated to the new version (0.0.2) but the buttons don't seem to be working.
did you forget to add the `media` folder? or it's a problem with me!
I tried to un/check the display buttons option in the settings but nothing is changing. I see no difference.

**Comment by jgoday** [comment]
Hi @kerolloz , I just uploaded a new version with your last pull request too (https://github.com/jgoday/vscode-exercism-extension/pull/3/) . Can you test it with the latest 0.0.4 version ?

**Comment by kerolloz** [comment]
@jgoday 
Works perfectly. :100: Thank you. :tada: :smiley:
