### ISSUE TITLE
**Bug:** `Submit Solution` submitted old version of code

### ISSUE THREAD

**Issue by sohang3112** [jgoday/vscode-exercism-extension#7]
When I ran the command `Exercism: Submit Solution`, it submitted an old version of the code, not the code that was currently saved. However, doing `exercism download` (directly from command line) worked correctly. So there is some issue with the extension code itself.

### Details
I downloaded [this Rust exercise](https://exercism.org/tracks/rust/exercises/space-age) using `Exercism: Fetch Solution` command, and then solved the challenge. However, when I submitted my solution using `Exercism: Submit Solution`, I noticed on the website that my actual code had not been submitted - instead, the initial dummy template code (generated by Exercism). I then tried submitting my code directly with the command `exercism submit src/lib.rs` - this submitted the correct code.

### Environment
- Windows 11
- VS Code version 1.68.1 (latest)

**Comment by sohang3112** [comment]
@jgoday Are you working on fixing this bug??

**Comment by jgoday** [comment]
> @jgoday Are you working on fixing this bug??

Hi @sohang3112, sorry for the delay.

I'm not able to reproduce this issue,
when 'Exercism: Submit current exercise' command is executed ('extension.exercism.submit'),
invokes cli 'exercism submit' over current project internally.

Command title is currently 'Exercism: Submit current exercise', not 'Exercism: Submit Solution', it seems strange ...

Could it be that you are referring to another extension?

**Comment by sohang3112** [comment]
It must be your extension only since it has your name in it in VS Code:

![Screenshot of VS Code Exercism extension](https://github.com/user-attachments/assets/64cf1685-c4c7-40c1-9e51-7c4282087869)

And these are the Exercism commands showing (these must be from your extension only, I don't have any other Exercism extension installed in VS Code):

![Screenshot of Exercism commands in VS Code](https://github.com/user-attachments/assets/6c564937-6cd8-494e-917f-f653ef229315)

**Comment by jgoday** [comment]
> It must be your extension only since it has your name in it in VS Code:
> 
Ok, you are right.

Can you check your exercism cli tool version ?
```
exercism version
```

**Comment by sohang3112** [comment]
Closing issue - upgrading Exercism CLI version fixed this issue. The command is working fine now with this Exercism CLI version:

```console
$ exercism version
exercism version 3.4.0
```

**Comment by jgoday** [comment]
> Closing issue - upgrading Exercism CLI version fixed this issue. The command is working fine now with this Exercism CLI version:
> 
> ```
> $ exercism version
> exercism version 3.4.0
> ```

Thank you @sohang3112 for your time!
